name: Draft release

on:
  - push
  - workflow_dispatch

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      #      - uses: actions/checkout@v2
      - name: Hello world action step
        uses: jackstr/release-changelog@v1
        with:
          who-to-greet: 'Mona the Octocat'

      #  env:
      #- uses: release-drafter/release-drafter@v5
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
